site_name: Algorithms illustrated by Python
site_author: ctn-admiralrua
pages:
- Home: 'index.md'
- Preparation:
    - 'Non-trivial preparation': 'week_01.md'
- About:
    - 'Release Notes': 'release-notes.md'
